import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync} from 'node:fs';
import {newGame,command} from '../src/simulation.js';
import {encode} from '../src/storage.js';
import {COMPUTER_GAMES,EMAIL_CATEGORIES} from '../src/computer.js';
import {FURNITURE} from '../src/security.js';

const url=process.env.DFP_TEST_URL||'http://127.0.0.1:4185',out='artifacts/computer';mkdirSync(out,{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true}),checks=[],errors=[];let context,p;
const pass=name=>{checks.push(name);console.log('PASS',name);};
const snap=()=>p.evaluate(()=>JSON.parse(JSON.parse(localStorage.getItem('dfp.save')).data));
const tap=(a,id)=>p.locator(`[data-computer="${a}"]${id?`[data-id="${id}"]`:''}`).first().tap();
async function launch(s,viewport={width:1440,height:950}){if(context)await context.close();context=await browser.newContext({viewport,hasTouch:true});await context.addInitScript(data=>{if(window!==window.top)return;if(!sessionStorage.getItem('seed')){localStorage.setItem('dfp.save',data);sessionStorage.setItem('seed','1');}},typeof s==='string'?s:encode(s));p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));await p.clock.install();await p.goto(url);await p.locator('[data-station]').first().waitFor();await p.clock.runFor(200);}
async function lounge(){await p.locator('[data-tab="elevator"]').tap();await p.locator('[data-action="basement-visit"]').tap();await p.clock.runFor(250);}
async function desktop(){await p.locator('#lounge-computer').tap();}
const base=()=>{const s=newGame();s.money=200;command(s,{type:'basement'});return s;};
const fixture=`<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><body style="margin:0;background:#e3f8dd;font:18px system-ui"><h1>Embedded control fixture</h1><button id="tap">Touch / click</button><input aria-label="Keyboard test"><p id="count">0</p><div style="height:800px">Scrollable game area</div><script>let n=0;document.querySelector('#tap').onclick=()=>document.querySelector('#count').textContent=++n;</script>`;
try{
 const poor=base();poor.money=99;await launch(poor);await lounge();await p.locator('#computer-buy').tap();assert.equal((await snap()).money,99);assert.equal((await snap()).basement.computer.owned,false);assert.match(await p.locator('#toast').textContent(),/Need \$1/);pass('$100 computer rejects $99 without a charge');
 const s=base();s.money=630;await launch(s);await lounge();await p.locator('#computer-buy').tap();assert.equal((await snap()).money,530);await p.clock.runFor(750);assert.ok((await p.locator('#lounge-canvas').evaluate(c=>c.dfpDiagnostics())).furniture.some(f=>f.id==='computer'));await desktop();await tap('security');assert.equal(await p.locator('#security-requirements li').count(),4);assert.ok(await p.locator('#security-buy').isDisabled());await tap('dfp');
 for(const item of FURNITURE)await p.locator(`[data-action="basement-furniture"][data-id="${item.id}"]`).tap();await p.clock.runFor(750);await p.screenshot({path:`${out}/basement-computer.png`});assert.equal(await p.locator('#lounge-tv').getAttribute('data-action'),null);await desktop();await p.screenshot({path:`${out}/desktop.png`});await tap('security');assert.equal(await p.locator('#security-requirements .complete').count(),4);await p.locator('#security-buy').tap();assert.equal((await snap()).money,200);assert.ok(await p.locator('.security-overlay').isVisible());await p.clock.runFor(550);await p.locator('[data-action="security-exit"]').tap();const sec=(await snap()).basement.security;assert.ok(await p.locator('#computer-view').isVisible());pass('Computer appears, TV is furnishing only; checklist gates the $150 system and cameras return to desktop');
 await tap('email');assert.ok((await p.locator('.app-unlock').textContent()).includes(`${EMAIL_CATEGORIES.map(cat=>cat.name).join(' and ')}. ${EMAIL_CATEGORIES.flatMap(cat=>cat.messages).length} fictional notes`));await tap('buy-email');assert.equal((await snap()).money,150);await p.screenshot({path:`${out}/email.png`});
 for(const cat of EMAIL_CATEGORIES){assert.equal(await p.locator(`[data-computer="inbox"][data-id="${cat.id}"] strong`).textContent(),cat.name);await tap('inbox',cat.id);assert.equal(await p.locator('.inbox-heading h2').textContent(),cat.name);assert.equal(await p.locator('.mail-row').count(),cat.messages.length);for(const msg of cat.messages){await tap('message',String(msg.id));assert.equal(await p.locator('.mail-message>p').textContent(),msg.body);await tap('inbox',cat.id);}await tap('email');}
 await p.clock.runFor(15000);assert.deepEqual((await snap()).basement.security,sec);assert.equal((await snap()).money,150);pass(`All ${EMAIL_CATEGORIES.reduce((total,cat)=>total+cat.messages.length,0)} original emails open and return correctly; reading mail does not advance security or change money`);
 await tap('desktop');await tap('store');await p.screenshot({path:`${out}/game-store.png`});let balance=150;for(const g of COMPUTER_GAMES){await tap('buy-game',g.id);balance-=50;assert.equal((await snap()).money,balance);assert.ok(await p.locator(`[data-computer="play"][data-id="${g.id}"]`).isVisible());}await p.reload();await p.clock.runFor(300);assert.equal((await snap()).money,0);const saved=await p.evaluate(()=>localStorage.getItem('dfp.save'));assert.ok(COMPUTER_GAMES.every(g=>(JSON.parse(JSON.parse(saved).data).basement.computer.games[g.id])));await lounge();await desktop();await tap('store');assert.equal(await p.locator('[data-computer="buy-game"]').count(),0);assert.equal(await p.locator('[data-computer="play"]').count(),3);pass('Three $50 games become Play, with owned state and exact balance preserved on reload');
 for(const g of COMPUTER_GAMES)await context.route(g.url,r=>r.fulfill({contentType:'text/html',body:fixture}));
 for(const g of COMPUTER_GAMES){await tap('play',g.id);const frame=p.frameLocator('#computer-game-area iframe');await frame.locator('#tap').waitFor();assert.equal(await p.locator('iframe').getAttribute('src'),g.url);assert.equal(await p.locator('iframe').getAttribute('sandbox'),'allow-scripts allow-same-origin allow-forms allow-pointer-lock');await frame.locator('#tap').tap();assert.equal(await frame.locator('#count').textContent(),'1');await frame.getByLabel('Keyboard test').fill('hello');assert.equal(await frame.getByLabel('Keyboard test').inputValue(),'hello');const child=p.frames().find(f=>f.url()===g.url);assert.equal(await child.evaluate(()=>{try{parent.localStorage.getItem('dfp.save');return false;}catch{return true;}}),true);await tap('desktop');assert.equal(await p.locator('iframe').count(),0);await tap('store');}pass('Controlled embedded fixtures verify all exact launch URLs, touch, keyboard, save isolation and frame/audio teardown');
 await tap('play','snake');await p.frameLocator('iframe').locator('#tap').waitFor();const beforeURL=p.url();const child=p.frames().find(f=>f.url()===COMPUTER_GAMES[2].url);assert.equal(await child.evaluate(()=>{try{top.location.href='https://example.invalid/';return false;}catch{return true;}}),true);assert.equal(p.url(),beforeURL);await tap('help');assert.match(await p.locator('.game-unavailable').textContent(),/blocked/);await tap('retry');await p.frameLocator('iframe').locator('#tap').waitFor();await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'));});assert.equal(await p.locator('iframe').count(),0);assert.match(await p.locator('.game-unavailable').textContent(),/paused/);await p.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));});await tap('dfp');assert.ok(await p.locator('#computer-view').isHidden());pass('Sandbox blocks top navigation; help/retry and background teardown preserve DFP and its exit controls');
 await desktop();await tap('store');await context.unroute(COMPUTER_GAMES[0].url);let pending;await context.route(COMPUTER_GAMES[0].url,route=>{pending=route;});await tap('play','boggle');await p.clock.runFor(20500);assert.match(await p.locator('.game-unavailable').textContent(),/too long/);assert.equal(await p.locator('iframe').count(),0);await pending?.abort().catch(()=>{});await context.unroute(COMPUTER_GAMES[0].url);await context.route(COMPUTER_GAMES[0].url,r=>r.fulfill({contentType:'text/html',body:fixture}));await tap('retry');await p.frameLocator('iframe').locator('#tap').waitFor();await tap('dfp');pass('A stalled game reaches a clear timeout and Retry restores its window without charging');
 for(const viewport of [{width:390,height:844},{width:844,height:390}]){
  await p.setViewportSize(viewport);await p.clock.runFor(200);await desktop();assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.ok(await p.locator('[data-computer="dfp"]').evaluate(el=>el.getBoundingClientRect().bottom<=innerHeight));await p.screenshot({path:`${out}/desktop-${viewport.width<500?'phone':'landscape'}.png`});await tap('email');await tap('inbox','funny');await tap('message',String(EMAIL_CATEGORIES.find(cat=>cat.id==='funny').messages.at(-1).id));await p.screenshot({path:`${out}/email-${viewport.width<500?'phone':'landscape'}.png`});await tap('desktop');await tap('store');await p.screenshot({path:`${out}/store-${viewport.width<500?'phone':'landscape'}.png`});await tap('play','boggle');await p.frameLocator('iframe').locator('#tap').tap();assert.ok(await p.locator('[data-computer="desktop"]').first().evaluate(el=>el.getBoundingClientRect().bottom<=innerHeight));await tap('dfp');assert.equal(await p.locator('iframe').count(),0);
 }pass('Portrait and landscape desktop/email/store and framed touch controls fit, with persistent return buttons');
 await p.evaluate(()=>navigator.serviceWorker.ready);await p.reload();await p.clock.runFor(300);await context.setOffline(true);await p.reload();await p.clock.runFor(300);await lounge();await desktop();await tap('email');assert.equal(await p.locator('.mail-category').count(),3);for(const cat of EMAIL_CATEGORIES){await tap('inbox',cat.id);const msg=cat.messages.at(-1);await tap('message',String(msg.id));assert.equal(await p.locator('.mail-message>p').textContent(),msg.body);await tap('inbox',cat.id);await tap('email');}await tap('desktop');await tap('security');assert.ok(await p.locator('.security-overlay').isVisible());await p.locator('[data-action="security-exit"]').tap();await tap('store');await tap('play','snake');assert.equal(await p.locator('iframe').count(),0);assert.match(await p.locator('.game-unavailable').textContent(),/offline/);assert.ok((await snap()).basement.computer.games.snake);await p.screenshot({path:`${out}/offline.png`});await tap('dfp');pass('Offline reload retains apps and games; email/security work, external game explains offline and Back to DFP works');
 await context.setOffline(false);
 const appPoor=base();appPoor.money=100;command(appPoor,{type:'computer'});appPoor.money=49;await launch(appPoor);await lounge();await desktop();await tap('email');await tap('buy-email');assert.equal((await snap()).money,49);assert.equal((await snap()).basement.computer.email,false);await tap('desktop');await tap('store');for(const game of COMPUTER_GAMES){await tap('buy-game',game.id);assert.equal((await snap()).money,49);assert.equal((await snap()).basement.computer.games[game.id],false);}pass('Email and all three game offers reject $49 in the UI without changing funds or ownership');
 const legacy=base();legacy.money=10000;command(legacy,{type:'computer'});for(const f of FURNITURE)command(legacy,{type:'furniture',id:f.id});command(legacy,{type:'security'});legacy.version=5;delete legacy.basement.computer;await launch(JSON.stringify(legacy));await lounge();assert.match(await p.locator('#computer-hint').textContent(),/already owned/);const money=(await snap()).money;await p.locator('#computer-buy').tap();assert.equal((await snap()).money,money-100);await desktop();await tap('security');assert.ok(await p.locator('.security-overlay').isVisible());assert.equal((await snap()).money,money-100);pass('Actual legacy browser save retains security and pays only for the new $100 computer');
 const probeContext=await browser.newContext({serviceWorkers:'block'});const probe=await probeContext.newPage();await probe.route(url+'/__frame_parent',r=>r.fulfill({contentType:'text/html',body:'<iframe sandbox="allow-scripts allow-same-origin allow-forms allow-pointer-lock" src="/__frame_child"></iframe>'}));await probe.route(url+'/__frame_child',r=>r.fulfill({contentType:'text/html',body:'<button>Game fixture</button>'}));await probe.goto(url+'/__frame_parent');const frame=probe.frames()[1];assert.equal(await frame.evaluate(()=>{try{top.location.href='/__unexpected';return false;}catch{return true;}}),true);assert.equal(probe.url(),url+'/__frame_parent');await probeContext.close();pass('Same-origin fixture confirms ordinary top navigation is blocked on a shared host');
 assert.deepEqual(errors,[]);writeFileSync(`${out}/browser-report.json`,JSON.stringify({checks,errors},null,2));
}catch(e){await p?.screenshot({path:`${out}/failure.png`}).catch(()=>{});throw e;}finally{await context?.close();await browser.close();}
