import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync} from 'node:fs';
import {newGame,command} from '../src/simulation.js';
import {encode} from '../src/storage.js';
import {FirebaseStore} from '../worker/firebase.js';
import {CommentService} from '../worker/core.js';
const url='http://127.0.0.1:4186',api='http://127.0.0.1:8787',out='artifacts/people-comments';mkdirSync(out,{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true}),contexts=[],errors=[],checks=[];let current;
const pass=name=>{checks.push(name);console.log('PASS',name);};
const seed=newGame();seed.money=1000;for(const type of ['basement','computer','email'])command(seed,{type});
const saved=encode(seed),balance=seed.money;
async function page(viewport={width:1280,height:900}){const c=await browser.newContext({viewport,hasTouch:true});contexts.push(c);await c.addInitScript(data=>{if(window!==window.top)return;if(!sessionStorage.getItem('people-seed')){localStorage.setItem('dfp.save',data);sessionStorage.setItem('people-seed','1');}},saved);const p=await c.newPage();current=p;p.on('pageerror',e=>errors.push(e.message));await p.goto(url);await p.locator('#game').waitFor();return p;}
async function desktop(p){await p.locator('[data-tab="elevator"]').tap();await p.locator('[data-action="basement-visit"]').tap();await p.locator('#lounge-computer').tap();}
const tap=(p,action)=>p.locator(`[data-people="${action}"]`).first().tap();
async function people(p){await p.locator('[data-computer="email"]').tap();await p.locator('[data-computer="people"]').tap();await p.locator('.people-status').filter({hasNotText:'Loading comments…'}).waitFor();}
async function fill(p,text,rating,audience){await p.locator('#comment-text').fill(text);await p.locator('#comment-rating').selectOption(String(rating));await p.locator('#comment-audience').selectOption(audience);if(audience==='producer')await p.locator('[name="acknowledged"]').check();}
async function send(p){await p.locator('#people-form [type="submit"]').tap();await p.locator('.people-receipt').waitFor();}
const authRoot='http://127.0.0.1:9099';
async function anon(){const r=await fetch(authRoot+'/identitytoolkit.googleapis.com/v1/accounts:signUp?key=demo-key',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({returnSecureToken:true})});return (await r.json()).idToken;}
const post=(path,body,token)=>fetch(api+path,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${token}`},body:JSON.stringify(body)});
try{
  // Test-only data lives solely in the demo emulator namespace.
  await fetch('http://127.0.0.1:9000/peopleComments.json?ns=demo-dfp-comments-default-rtdb',{method:'DELETE',headers:{authorization:'Bearer owner'}});
  const a=await page();await desktop(a);assert.equal(await a.locator('[data-computer="producer"]').count(),0);await people(a);
  assert.equal(await a.locator('.people-empty').textContent(),'No comments in this view yet.');pass('People Comments is separate from fictional mail; Producer is hidden for ordinary players');
  await tap(a,'add');await a.locator('#comment-audience').selectOption('producer');assert.match(await a.locator('.people-privacy').textContent(),/Only the game’s producer/);assert.ok(await a.locator('[name="acknowledged"]').isVisible());
  await a.locator('#comment-text').fill('   ');await a.locator('#comment-rating').selectOption('1');await a.locator('[name="acknowledged"]').check();await a.locator('#people-form [type="submit"]').tap();await a.getByText('Write a comment, not just spaces.').waitFor();
  await fill(a,'The game is slow and the food is cold.',1,'everyone');assert.match(await a.locator('.people-privacy').textContent(),/visible to all players/);await send(a);assert.equal(await a.locator('.people-receipt h2').textContent(),'Published');pass('Private warning/acknowledgement and nonblank validation work; appropriate one-star criticism publishes');
  const b=await page({width:390,height:844});await desktop(b);await people(b);await b.getByText('The game is slow and the food is cold.',{exact:true}).waitFor();
  await b.locator('#people-stars').selectOption('5');await b.locator('.people-empty').waitFor();await b.locator('#people-stars').selectOption('1');await b.getByText('The game is slow and the food is cold.',{exact:true}).waitFor();
  await b.locator('#people-audience').selectOption('producer');assert.match(await b.locator('.people-results').textContent(),/cannot browse private feedback/);await tap(b,'add-private');await fill(b,'Please add more tables.',2,'producer');await b.screenshot({path:`${out}/private-form-phone.png`});await send(b);assert.equal(await b.locator('.people-receipt h2').textContent(),'Sent to Producer');
  await tap(a,'back');await tap(a,'refresh');assert.equal(await a.getByText('Please add more tables.',{exact:true}).count(),0);pass('Independent sessions share public comments, exact-star filters work, and private feedback stays out of the public feed');
  const token=await anon(),uncertain={text:'Quizzical confetti!',rating:3,audience:'producer',acknowledged:true,requestId:crypto.randomUUID()};
  const responses=await Promise.all(Array.from({length:5},()=>post('/comments',uncertain,token).then(r=>r.json())));assert.ok(responses.every(r=>r.status==='pending'&&r.id===responses[0].id));
  assert.equal((await post('/comments',{...uncertain,rating:4},token)).status,409);assert.equal((await fetch(api+'/owner/comments?audience=producer',{headers:{authorization:`Bearer ${token}`}})).status,403);pass('Concurrent retries return one pending submission; changed payloads and anonymous private requests are denied');
  const rejected=await page();await desktop(rejected);await people(rejected);await tap(rejected,'add');await fill(rejected,'f.u.c.k',4,'everyone');await rejected.locator('#people-form [type="submit"]').tap();await rejected.getByText(/Rejected\. Please remove/).waitFor();assert.equal(await rejected.locator('#comment-text').inputValue(),'f.u.c.k');pass('Disguised profanity is rejected by the real local backend and stays editable');
  const requester=await page();await desktop(requester);await requester.locator('[data-computer="producer-signin"]').tap();await tap(requester,'send-link');await requester.getByText(/Sign-in email sent/).waitFor();assert.ok(await requester.locator('[data-people="send-link"]').isDisabled());assert.equal(await requester.locator('[data-computer="producer"]').count(),0);
  const oobData=await (await fetch(authRoot+'/emulator/v1/projects/demo-dfp-comments/oobCodes')).json();const mail=oobData.oobCodes.filter(x=>x.email==='lucaessey@gmail.com').at(-1);assert.ok(mail);const link=new URL(url);link.search=new URL(mail.oobLink).search;
  const owner=await page();await owner.goto(link.href);await owner.locator('#producer-email').waitFor();assert.equal(await owner.locator('#producer-email').inputValue(),'');assert.ok(!owner.url().includes('oobCode'));
  await owner.locator('#producer-email').fill('other@example.com');await tap(owner,'complete-link');await owner.getByText(/Enter the producer email address/).waitFor();assert.equal(await owner.locator('[data-computer="producer"]').count(),0);
  await owner.locator('#producer-email').fill('lucaessey@gmail.com');await tap(owner,'complete-link');await owner.getByText(/Producer verified/).waitFor();await owner.locator('#producer-link-close').tap();await desktop(owner);await owner.locator('[data-computer="producer"]').waitFor();assert.equal(await owner.locator('.desktop-app').count(),4);await owner.locator('[data-computer="producer"]').tap();await owner.getByText('Please add more tables.',{exact:true}).waitFor();
  await tap(owner,'read');await owner.getByText('Private · Producer · Read',{exact:true}).waitFor();pass('Auth emulator email-link flow, cooldown, different-device confirmation, verified owner app and mark-read work');
  await owner.locator('#people-audience').selectOption('pending');await owner.locator('#people-stars').selectOption('3');await owner.getByText('Quizzical confetti!',{exact:true}).waitFor();await owner.screenshot({path:`${out}/producer-pending.png`});await tap(owner,'approve');await owner.locator('.people-empty').waitFor();await owner.locator('#people-audience').selectOption('producer');await owner.getByText('Quizzical confetti!',{exact:true}).waitFor();await tap(a,'refresh');assert.equal(await a.getByText('Quizzical confetti!',{exact:true}).count(),0);pass('Producer pending-star filters and approval retain the original private audience');
  await a.locator('#people-stars').selectOption('1');await a.getByText('The game is slow and the food is cold.',{exact:true}).waitFor();await tap(a,'report');await a.getByText(/Reported\. The comment is private/).waitFor();await owner.locator('#people-audience').selectOption('pending');await owner.locator('#people-stars').selectOption('1');await owner.getByText('The game is slow and the food is cold.',{exact:true}).waitFor();await tap(owner,'approve');await owner.locator('#people-audience').selectOption('everyone');await owner.getByText('The game is slow and the food is cold.',{exact:true}).waitFor();await tap(owner,'hide');await owner.locator('.people-empty').waitFor();await tap(a,'refresh');await a.locator('.people-empty').waitFor();pass('Public reports enter private review; owner approval and hiding update the public feed');
  // Seed pagination fixtures through the same service, with a test-only disabled quota.
  const fixtureService=new CommentService({db:new FirebaseStore({base:'http://127.0.0.1:9000',namespace:'demo-dfp-comments-default-rtdb',token:async()=> 'owner'}),limits:{consume:async()=>{}}});
  for(let n=0;n<45;n++)await fixtureService.submit({text:'Good game.',rating:n%5+1,audience:'everyone',requestId:crypto.randomUUID()},{uid:'fixture'+n,ip:'fixture'});
  await tap(b,'back');await b.locator('#people-stars').selectOption('all');await b.locator('.people-comment').first().waitFor();assert.equal(await b.locator('.people-comment').count(),20);await tap(b,'more');await b.locator('.people-comment').nth(39).waitFor();assert.equal(await b.locator('.people-comment').count(),40);await tap(b,'more');await b.locator('.people-comment').nth(44).waitFor();assert.equal(await b.locator('.people-comment').count(),45);
  const addRect=await b.locator('[data-people="add"]').boundingBox();assert.ok(addRect.y+addRect.height<844);await b.screenshot({path:`${out}/comments-phone.png`});await b.setViewportSize({width:844,height:390});assert.ok(await b.locator('[data-people="add"]').isVisible());assert.equal(await b.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await b.screenshot({path:`${out}/comments-landscape.png`});pass('Three bounded pages load without repeats; sticky Add Comment fits portrait and landscape');
  await tap(b,'add');await fill(b,'Please add more games.',4,'producer');await b.context().setOffline(true);await b.getByText(/You’re offline/).waitFor();assert.ok(await b.locator('#people-form [type="submit"]').isDisabled());await b.evaluate(()=>navigator.serviceWorker.ready);await b.reload();await b.locator('#game').waitFor();await desktop(b);await people(b);await tap(b,'add');assert.equal(await b.locator('#comment-text').inputValue(),'Please add more games.');assert.equal(await b.locator('#comment-audience').inputValue(),'producer');assert.equal(await b.locator('.people-receipt').count(),0);assert.equal(await b.evaluate(()=>JSON.parse(JSON.parse(localStorage.getItem('dfp.save')).data).money),balance);pass('Offline reload preserves the unposted private draft and existing game purchases/balance');
  await b.context().setOffline(false);
  await owner.locator('#people-audience').selectOption('producer');await owner.locator('#people-stars').selectOption('all');await owner.getByText('Please add more tables.',{exact:true}).waitFor();await owner.context().setOffline(true);await owner.getByText('Producer Sign-in',{exact:true}).last().waitFor();assert.equal(await owner.getByText('Please add more tables.',{exact:true}).count(),0);await owner.context().setOffline(false);
  await owner.locator('[data-computer="desktop"]').tap();await owner.locator('[data-computer="producer"]').waitFor();await owner.locator('[data-computer="producer"]').tap();await owner.getByText('Please add more tables.',{exact:true}).waitFor();let delayedResolve;const delayed=new Promise(resolve=>delayedResolve=resolve);await owner.route('http://127.0.0.1:9000/peopleComments/private/all.json**',route=>delayedResolve(route));await tap(owner,'refresh');const delayedRoute=await delayed;await tap(owner,'signout');await owner.getByText(/Signed out/).waitFor();await delayedRoute.fulfill({contentType:'application/json',body:JSON.stringify({'9999999999999_late':{text:'LATE PRIVATE SECRET',id:'a'.repeat(48),rating:5,createdAt:Date.now()}})}).catch(()=>{});await owner.unroute('http://127.0.0.1:9000/peopleComments/private/all.json**');assert.equal(await owner.getByText('LATE PRIVATE SECRET').count(),0);assert.equal(await owner.getByText('Please add more tables.',{exact:true}).count(),0);await owner.locator('[data-computer="desktop"]').tap();assert.equal(await owner.locator('[data-computer="producer"]').count(),0);pass('Offline clears private data; reconnect reauthorizes; sign-out cancels an in-flight read and discards late private data');
  const reused=await page();await reused.goto(link.href);await reused.locator('#producer-email').fill('lucaessey@gmail.com');await tap(reused,'complete-link');await reused.getByText(/expired, already used/).waitFor();assert.equal(await reused.locator('[data-computer="producer"]').count(),0);pass('A reused email link cannot grant Producer access');
  assert.deepEqual(errors,[]);writeFileSync(`${out}/browser-report.json`,JSON.stringify({checks,errors},null,2));console.log(`${checks.length} browser checks passed.`);
}catch(e){await current?.screenshot({path:`${out}/failure.png`}).catch(()=>{});throw e;}finally{await Promise.all(contexts.map(c=>c.close()));await browser.close();}
