import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync} from 'node:fs';
import {newGame,command,step} from '../src/simulation.js';
import {encode} from '../src/storage.js';
import {PETS} from '../src/pets.js';
import {PRODUCTS,LAYOUTS,FLOOR_FOODS,customerQueue,checkoutQueue} from '../src/config.js';
const base=process.env.DFP_TEST_URL||'http://127.0.0.1:4173/',out='artifacts/pets';mkdirSync(out,{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true}),checks=[],errors=[],performance=[];
let context,page;
const pass=message=>{checks.push(message);console.log('PASS',message);};
async function open(seed,viewport={width:390,height:844},touch=true){if(context)await context.close();context=await browser.newContext({viewport,isMobile:touch,hasTouch:touch});await context.addInitScript(data=>{if(!sessionStorage.seeded){localStorage.setItem('dfp.save',data);sessionStorage.seeded='1';}},encode(seed));page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.clock.install();await page.goto(base);await page.locator('[data-tab="pets"]').waitFor();await page.clock.runFor(250);}
const press=async selector=>page.locator(selector).press('Enter');
const snap=()=>page.evaluate(()=>JSON.parse(JSON.parse(localStorage.getItem('dfp.save')).data));
const advance=ms=>page.clock.runFor(ms);
const until=async(pred,label,limit=50000)=>{for(let t=0;t<limit;t+=500){if(await pred())return;await advance(500);}throw Error(label);};
function rich(f=0){const s=newGame();s.money=100000;for(let i=1;i<4;i++)command(s,{type:'floor',floor:i});for(const p of PRODUCTS)command(s,{type:'product',floor:p.floor,id:p.id});command(s,{type:'visit',floor:f});command(s,{type:'basement'});command(s,{type:'computer'});for(const fs of s.floors)fs.arrival=100;return s;}
try{
 const first=newGame();await open(first,{width:320,height:700});await page.locator('[data-tab="pets"]').tap();await advance(250);assert.equal(await page.locator('.pet-card').count(),30);assert.equal(await page.locator('[data-tab]').count(),5);
 for(const button of await page.locator('[data-tab]').all()){const b=await button.boundingBox();assert.ok(b.x>=0&&b.x+b.width<=321&&b.height>=40);}
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.ok(await page.locator('[data-pet-card="whale"] [data-pet-command]').isDisabled());await page.locator('[data-pet-card="chick"] [data-pet-command]').tap();await advance(200);assert.equal((await snap()).money,100);assert.equal((await snap()).pets.equipped,'chick');await page.locator('[data-pet-card="bunny"] [data-pet-command]').tap();await advance(200);assert.equal((await snap()).money,65);assert.equal((await snap()).pets.equipped,'bunny');await page.locator('#panel-view').evaluate(e=>e.scrollTop=0);await page.screenshot({path:`${out}/shop-320.png`});
 await press('.pet-purchase');await advance(100);assert.equal((await snap()).pets.equipped,null);await press('[data-pet-card="chick"] [data-pet-command]');await advance(100);assert.equal((await snap()).money,65);await page.reload();await advance(300);assert.deepEqual((await snap()).pets.owned,['chick','bunny']);assert.equal((await snap()).pets.equipped,'chick');pass('320px touch shop: five accessible tabs, 30 pets, locked state, correct charges, free switching, unequip and reload');
 await page.evaluate(()=>navigator.serviceWorker.ready);await page.reload();await advance(250);await context.setOffline(true);await page.reload();await advance(300);await press('[data-tab="pets"]');await advance(300);assert.equal(await page.locator('.pet-card').count(),30);assert.equal((await snap()).money,65);assert.equal((await snap()).pets.equipped,'chick');pass('Offline production reload preserves pet ownership, equipment, money and all local preview assets');await context.setOffline(false);
 const all=rich();for(const p of PETS)command(all,{type:'pet-buy',id:p.id});await open(all,{width:1440,height:1000},false);await press('[data-tab="pets"]');await advance(300);
 const thumbs=await page.locator('.pet-card').evaluateAll(cards=>cards.map(c=>({name:c.querySelector('h2').textContent,src:c.querySelector('img').src})));
 for(const p of PETS){await press(`[data-pet-select="${p.id}"]`);await advance(70);const d=await page.locator('.pet-preview canvas').evaluate(c=>c.dfpDiagnostics());assert.equal(d.selected,p.id);assert.equal(d.animatedModels,1);assert.equal(d.thumbnailCount,30);assert.ok(d.calls<70);performance.push({pet:p.id,calls:d.calls,triangles:d.triangles});}
 await page.screenshot({path:`${out}/shop-desktop.png`});pass('All 30 selected 3D previews render with one animated model and cached still thumbnails');
 const sheet=await context.newPage();await sheet.setViewportSize({width:1250,height:1250});await sheet.setContent(`<style>body{margin:0;background:#fff4df;color:#38535b;font:15px Arial}h1{text-align:center}.grid{display:grid;grid-template-columns:repeat(6,1fr);gap:10px;padding:20px}article{background:#e6e0f3;border-radius:18px;text-align:center;padding:4px}img{width:100%;height:160px;object-fit:contain}b{display:block;margin-bottom:10px}</style><h1>DFP • All 30 pixel pals</h1><div class="grid">${thumbs.map(t=>`<article><img src="${t.src}"><b>${t.name}</b></article>`).join('')}</div>`);await sheet.screenshot({path:`${out}/collection.png`,fullPage:true});await sheet.close();
 await page.setViewportSize({width:844,height:390});await advance(200);for(const nav of await page.locator('[data-tab]').all()){const b=await nav.boundingBox();assert.ok(b.y>=0&&b.y+b.height<=391,'Landscape navigation stays visible');}await page.locator('#panel-view').evaluate(e=>e.scrollTop=0);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:`${out}/shop-landscape.png`});pass('Desktop and landscape shop stays within viewport');
 for(let f=0;f<4;f++){
  const s=rich(f);command(s,{type:'pet-buy',id:['dragon','bunny','robot','whale'][f]});command(s,{type:'hire',floor:f,id:f*5});
  // The player starts at production; an existing waiting customer needs one item.
  const item=f<2?FLOOR_FOODS[f][0]:f===2?'souvenir':null,source=f===0?'prep':f===1?'tower':f===2?'stock':'machine0';
  Object.assign(s.player,LAYOUTS[f].find(st=>st.id===source).pad);
  s.floors[f].arrival=0;step(s,.05,{pausedPlayer:true});const c=s.floors[f].customers[0];if(item){c.needs=[item];c.delivered=[false];if(f<2)Object.assign(c,customerQueue(s.floors[f],f,c));}
  s.floors[f].arrival=100;s.employees[0].x=20;s.employees[0].y=15;
  await open(s);await advance(900);
  if(f===0){await press('[data-station="fry"]');await advance(4500);await press('[data-station="pickup"]');await until(async()=>!!(await snap()).player.bag.length,'pickup food');}
  if(f<2){await until(async()=>!!(await snap()).player.bag.length,'make meal');await press('[data-station="stack"]');await until(async()=>!(await snap()).player.bag.length,'stack food');await press('[data-station="counter"]');}
  if(f===2){await until(async()=>!!(await snap()).player.bag.length,'pick up shop goods');await press('[data-station="shelf"]');await until(async()=>!(await snap()).player.bag.length,'restock shop shelf');await press('[data-station="checkout"]');}
  await until(async()=>(await snap()).floors[f].revenue>0,'job pays',60000);await advance(500);
  const d=await page.locator('#game').evaluate(c=>c.dfpDiagnostics());assert.equal(d.pet.models,1);assert.equal(d.pet.id,s.pets.equipped);assert.ok(Math.hypot(d.pet.x-(await snap()).player.x,d.pet.y-(await snap()).player.y)<3);performance.push({floor:f+1,calls:d.calls,triangles:d.triangles});await page.screenshot({path:`${out}/floor-${f+1}.png`});
  await press('#area-button');await until(async()=> (await snap()).player.x>19,'follow to dining');await advance(2000);const dining=await page.locator('#game').evaluate(c=>c.dfpDiagnostics());assert.ok(Math.hypot(dining.pet.x-(await snap()).player.x,dining.pet.y-(await snap()).player.y)<2.5);await page.screenshot({path:`${out}/floor-${f+1}-following.png`});pass(`Floor ${f+1}: player job, real revenue, one equipped companion and following around furniture into dining`);
  await press('[data-tab="elevator"]');await press(`[data-action="visit"][data-floor="${(f+1)%4}"]`);await advance(300);assert.equal((await page.locator('#game').evaluate(c=>c.dfpDiagnostics())).pet.id,s.pets.equipped);
 }
 const staffed=rich();for(const fs of staffed.floors)fs.arrival=.1;command(staffed,{type:'pet-buy',id:'phoenix'});for(let f=0;f<4;f++)command(staffed,{type:'hire',floor:f,id:f*5});await open(staffed);await press('[data-tab="pets"]');await advance(95000);const worked=await snap();for(const fs of worked.floors)assert.ok(fs.revenue>0);pass('Employees complete jobs on all four floors while the pet shop is open; pet helpers remain paused');
 await press('[data-tab="elevator"]');await press('[data-action="basement-visit"]');await advance(400);assert.equal(await page.locator('#lounge-canvas').evaluate(c=>c.dfpDiagnostics().pet),'phoenix');await page.screenshot({path:`${out}/basement.png`});
 await press('[data-tab="pets"]');await press('.pet-remove');await press('[data-tab="home"]');await advance(200);assert.equal(await page.locator('#lounge-canvas').evaluate(c=>c.dfpDiagnostics().pet),null);pass('Basement shows only the equipped companion; unequip removes it immediately');
 await press('[data-tab="pets"]');await press('[data-pet-card="phoenix"] [data-pet-command]');await press('[data-tab="elevator"]');await press('[data-action="visit"][data-floor="0"]');await advance(200);await press('[data-action="settings"]');await press('[data-action="motion"]');await press('[data-action="close"]');await advance(600);assert.equal((await snap()).settings.reducedMotion,true);assert.equal((await page.locator('#game').evaluate(c=>c.dfpDiagnostics())).pet.id,'phoenix');pass('Reduced motion retains the companion and gameplay state');
 assert.deepEqual(errors,[]);writeFileSync(`${out}/report.json`,JSON.stringify({checks,performance,errors},null,2));writeFileSync(`${out}/index.html`,`<!doctype html><meta charset="utf-8"><title>DFP pets verification</title><style>body{font:16px system-ui;max-width:1100px;margin:40px auto;background:#fff6e6;color:#345}img{max-width:100%;border-radius:18px}section{display:flex;gap:15px;flex-wrap:wrap}section img{max-width:360px}</style><h1>DFP · Your pixel pals</h1><p>${checks.length} browser checks passed. Isolated test saves; actual progress was not changed.</p><img src="collection.png"><section>${['shop-320','floor-1','floor-2','floor-3','floor-4','basement'].map(n=>`<img src="${n}.png">`).join('')}</section>`);
}finally{await context?.close();await browser.close();}
