import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync} from 'node:fs';
import {newGame,command,step} from '../src/simulation.js';
import {FURNITURE,ensureSecurityRound} from '../src/security.js';
import {PRODUCTS} from '../src/config.js';
import {encode} from '../src/storage.js';

const url=process.env.DFP_TEST_URL||'http://127.0.0.1:4185',out='artifacts/basement';mkdirSync(out,{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true}),checks=[],errors=[];let context,p;
const snap=()=>p.evaluate(()=>JSON.parse(JSON.parse(localStorage.getItem('dfp.save')).data));
async function launch(s,viewport={width:1440,height:900}){if(context)await context.close();context=await browser.newContext({viewport,hasTouch:true});await context.addInitScript(data=>{if(!sessionStorage.getItem('seed')){localStorage.setItem('dfp.save',data);sessionStorage.setItem('seed','1');}},encode(s));p=await context.newPage();p.on('pageerror',e=>{errors.push(e.message);console.log('BROWSER ERROR',e.message);});await p.clock.install();await p.goto(url);await p.locator('[data-station]').first().waitFor();await p.clock.runFor(200);}
async function visit(){await p.locator('[data-tab="elevator"]').tap();await p.locator('[data-action="basement-visit"]').tap();await p.clock.runFor(300);}
async function watch(){await p.locator('#lounge-tv').tap();await p.clock.runFor(200);}
async function until(test,label,max=160){for(let i=0;i<max;i++){if(test(await snap()))return;await p.clock.runFor(250);}throw Error(label);}
function ready(f=0){const s=newGame();s.money=100000;command(s,{type:'basement'});for(const item of FURNITURE)command(s,{type:'furniture',id:item.id});command(s,{type:'security'});for(let i=1;i<=f;i++)command(s,{type:'floor',floor:i});for(const product of PRODUCTS.filter(p=>p.floor<=f))command(s,{type:'product',floor:product.floor,id:product.id});command(s,{type:'hire',floor:f,id:f*5});for(let i=0;i<380;i++)step(s,.05,{pausedPlayer:true});ensureSecurityRound(s);return s;}
const pass=label=>{checks.push(label);console.log('PASS',label);};
try{
 const poor=newGame();poor.money=199;await launch(poor,{width:390,height:844});await p.locator('[data-tab="elevator"]').tap();assert.equal(await p.locator('[data-tab]').count(),4);assert.match(await p.locator('[data-action="basement-buy"]').textContent(),/\$200/);await p.locator('[data-action="basement-buy"]').tap();assert.equal((await snap()).money,199);assert.equal((await snap()).basement.unlocked,false);assert.equal(await p.locator('#toast').getAttribute('data-tone'),'error');await p.screenshot({path:`${out}/elevator-phone.png`});pass('Basement visible before food/upper unlocks; $199 cannot buy it; four bottom tabs retained');
 const s=newGame();s.money=530;await launch(s);await p.locator('[data-tab="elevator"]').tap();await p.locator('[data-action="basement-buy"]').tap();assert.equal((await snap()).money,330);await p.locator('[data-action="basement-visit"]').tap();await p.clock.runFor(300);assert.ok(await p.locator('#security-buy').isDisabled());let cash=330;
 for(const item of FURNITURE){await p.locator(`[data-action="basement-furniture"][data-id="${item.id}"]`).tap();cash-=item.cost;assert.equal((await snap()).money,cash);await p.clock.runFor(200);const d=await p.locator('#lounge-canvas').evaluate(c=>c.dfpDiagnostics());assert.ok(d.furniture.find(o=>o.id===item.id)?.building);if(item.id!=='plant2')assert.ok(await p.locator('#security-buy').isDisabled());}
 assert.equal(await p.locator('#security-requirements .complete').count(),4);await p.locator('#security-buy').tap();assert.equal((await snap()).money,0);await p.clock.runFor(800);await p.screenshot({path:`${out}/lounge-desktop.png`});await p.reload();await p.clock.runFor(200);assert.ok((await snap()).basement.security.owned);assert.equal((await snap()).money,0);await visit();assert.ok((await p.locator('#lounge-canvas').evaluate(c=>c.dfpDiagnostics())).furniture.every(o=>!o.building));pass('All furniture prices, four-part checklist, $150 security, placement animation and reload ownership');
 await watch();const initial=await snap();assert.match(await p.locator('#security-floor').textContent(),/1 · The Takeout/);await p.locator('[data-action="security-exit"]').tap();const paused=(await snap()).basement.security.round;await p.clock.runFor(35000);assert.deepEqual((await snap()).basement.security.round,paused);await p.reload();await p.clock.runFor(500);assert.deepEqual((await snap()).basement.security.round,paused);await visit();await watch();await until(s=>s.basement.security.round.phase==='active','robber arrival');assert.equal(await p.locator('[data-person="robber"]').count(),1);await p.screenshot({path:`${out}/security-desktop.png`});
 const before=(await snap()).money;await p.locator('[data-person="robber"]').tap();await p.clock.runFor(100);assert.equal((await snap()).money,before+15);assert.match(await p.locator('#security-feedback').textContent(),/Caught! \+\$15/);await p.reload();await p.clock.runFor(500);assert.equal((await snap()).money,before+15);pass('Closed/reloaded monitoring freezes its wait; one robber appears and catch pays exactly $15 once');

 for(let floor=0;floor<4;floor++){
  const s=ready(floor);s.basement.security.round.remaining=1;await launch(s,{width:390,height:844});await visit();if(floor===0)await p.screenshot({path:`${out}/lounge-phone.png`});await watch();await until(s=>s.basement.security.round.phase==='active','active phone robber');await p.clock.runFor(2400);
  assert.equal((await snap()).floor,0);assert.match(await p.locator('#security-floor').textContent(),new RegExp(`^${floor+1} ·`));const d=await p.locator('#security-canvas').evaluate(c=>c.dfpDiagnostics());assert.equal(d.floor,floor);assert.ok(d.positions.some(a=>a.key.startsWith('staff')));assert.ok(d.positions.some(a=>a.key.startsWith('guest')));assert.ok(d.positions.some(a=>a.key==='robber'&&a.motion==='stealing'));assert.equal(await p.locator('[data-tab]').count(),4);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.screenshot({path:`${out}/security-floor-${floor+1}-phone.png`});
  const r=(await snap()).basement.security.round;await p.locator('[data-action="security-exit"]').tap();const stopped=(await snap()).basement.security.round;await p.clock.runFor(13000);assert.deepEqual((await snap()).basement.security.round,stopped);await watch();assert.ok((await snap()).basement.security.round.remaining<=r.remaining);await p.setViewportSize({width:844,height:390});await p.clock.runFor(350);assert.equal(await p.locator('[data-person="robber"]').count(),1);assert.ok(await p.locator('.bottom-nav').evaluate(el=>el.getBoundingClientRect().bottom<=innerHeight));await p.screenshot({path:`${out}/security-floor-${floor+1}-landscape.png`});if(floor%2===0){await p.setViewportSize({width:390,height:844});await p.clock.runFor(200);}await p.locator('[data-person="robber"]').tap();await p.clock.runFor(50);assert.equal((await snap()).basement.security.catches,1);pass(`Floor ${floor+1}: live actual layout, customers, staff, theft pose, phone target and active pause/resume`);
 }
 const wrong=ready(0);wrong.employees[0].x=7;wrong.employees[0].y=5;wrong.basement.security.round.remaining=1;await launch(wrong);await visit();await watch();await until(s=>s.basement.security.round.phase==='active','wrong-person setup');const old=(await snap()).basement.security;await p.locator('[data-person="staff-0"]').click();await p.clock.runFor(50);assert.equal((await snap()).basement.security.wrong,old.wrong+1);assert.equal((await snap()).basement.security.penalties,5);assert.equal((await snap()).basement.security.round.id,old.round.id);assert.match(await p.locator('#security-feedback').textContent(),/innocent/);await until(s=>s.basement.security.escapes===1,'escape');assert.equal((await snap()).basement.security.penalties,10);assert.match(await p.locator('#security-feedback').textContent(),/escaped/);pass('Wrong selection and escape each charge $5; wrong selection does not end the active encounter');
 await p.keyboard.press('Escape');assert.ok(await p.locator('.security-overlay').isHidden());await p.locator('#lounge-tv').focus();await p.keyboard.press('Enter');await p.clock.runFor(100);assert.ok(await p.locator('.security-overlay').isVisible());const camera=await p.locator('#security-canvas').evaluate(c=>c.dfpDiagnostics().camera);await p.keyboard.press('ArrowRight');await p.clock.runFor(500);assert.notDeepEqual(await p.locator('#security-canvas').evaluate(c=>c.dfpDiagnostics().camera),camera);await p.setViewportSize({width:844,height:390});await p.clock.runFor(300);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.screenshot({path:`${out}/security-landscape.png`});pass('Keyboard TV activation, camera panning and Escape exit; landscape controls fit');
 await p.evaluate(()=>window.dispatchEvent(new Event('blur')));const frozen=(await snap()).basement.security;await p.clock.runFor(35000);assert.deepEqual((await snap()).basement.security,frozen);await p.evaluate(()=>window.dispatchEvent(new Event('focus')));await p.clock.runFor(200);await p.locator('[data-action="security-exit"]').tap();assert.notEqual((await snap()).basement.security.round.remaining,frozen.round.remaining);pass('Focus loss pauses the encounter clock with no hidden penalty');
 await watch();await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'));});const hidden=(await snap()).basement.security;await p.clock.runFor(35000);assert.deepEqual((await snap()).basement.security,hidden);await p.evaluate(()=>{delete document.hidden;document.dispatchEvent(new Event('visibilitychange'));});await p.clock.runFor(200);await p.locator('[data-action="security-exit"]').tap();assert.notEqual((await snap()).basement.security.round.remaining,hidden.round.remaining);pass('Visibility-change handler freezes and resumes the saved encounter without away-time outcomes');
 const oldRound=(await snap()).basement.security.round.id;await p.locator('[data-tab="elevator"]').tap();await p.locator('[data-action="unlock-floor"][data-floor="1"]').tap();await p.locator('[data-action="basement-visit"]').tap();await p.clock.runFor(200);await watch();assert.match(await p.locator('#security-floor').textContent(),/^2 ·/);assert.equal((await snap()).basement.security.round.id,oldRound);await p.locator('[data-action="security-exit"]').tap();pass('A newly unlocked upper floor automatically becomes the monitored floor without restarting the saved round');
 await p.evaluate(()=>navigator.serviceWorker.ready);await p.reload();await p.clock.runFor(200);await context.setOffline(true);await p.reload();await p.clock.runFor(200);await visit();await watch();assert.ok((await snap()).basement.security.owned);assert.ok(await p.locator('#security-canvas').evaluate(c=>c.dfpDiagnostics().calls>0));await p.screenshot({path:`${out}/security-offline.png`});pass('Offline reload retains the lounge/security and renders live monitoring');
 assert.deepEqual(errors,[]);writeFileSync(`${out}/browser-report.json`,JSON.stringify({checks,errors},null,2));
}catch(e){if(p)await p.screenshot({path:`${out}/failure.png`}).catch(()=>{});throw e;}finally{if(context)await context.close();await browser.close();}
