import test from 'node:test';
import assert from 'node:assert/strict';
import {newGame,step,command} from '../src/simulation.js';
import {encode,decode,validateSave} from '../src/storage.js';
import {newStory,startStory,pauseStory,resumeStory,storyVisit,sendChallenge,leaveStoryComputer,storyObjective,startStoryEvent,storyEventAction,storyTick,continueStory,currentStoryActor,storyScene,validateStory} from '../src/story.js';
import {STORY_OBJECTIVES,STORY_PLACES,RECIPES,EVENT_SPOTS,eventRules} from '../src/story-data.js';
import {storyPath,storyWalkable,storyDistance} from '../src/story-navigation.js';
import {character} from '../src/scene-assets.js';
import {animateStickman} from '../src/character-motion.js';
import {OUTFITS} from '../src/config.js';

function ready(){const s=newGame();s.basement.unlocked=true;s.basement.computer.owned=true;s.basement.computer.email=true;s.settings.sound=false;return s;}
const tick=(s,seconds,input={})=>{for(let t=0;t<seconds;t+=.05)storyTick(s,.05,input);};
function go(s,p){let n=0;while(storyDistance(currentStoryActor(s.story),p)>.12&&n++<2400)storyTick(s,.05,{target:p});assert.ok(n<2400,`Reach ${JSON.stringify(p)} in ${storyScene(s.story)}`);}
function setObjective(s,id){startStory(s);const i=STORY_OBJECTIVES.findIndex(o=>o.id===id);s.story.index=i;s.story.clues=STORY_OBJECTIVES.slice(0,i).filter(o=>o.kind==='talk').map(o=>o.id);s.story.wins=STORY_OBJECTIVES.slice(0,i).filter(o=>o.kind==='event').map(o=>({id:o.id,score:30,rival:0,elapsed:20}));if(i>2)s.story.emails=['intro','challenge','reply'];s.story.actor.x=23;s.story.actor.y=12;s.story.location='outside';}
const action=(s,name,id)=>assert.equal(storyEventAction(s,name,id).ok,true,`${name} ${id}`);
function winCook(s){for(const index of s.story.event.orders){const recipe=RECIPES[index];for(const ingredient of recipe.ingredients){go(s,EVENT_SPOTS[ingredient]);action(s,'ingredient',ingredient);}go(s,EVENT_SPOTS.prep);action(s,'prepare',recipe.id);tick(s,2.6);go(s,EVENT_SPOTS.serve);action(s,'deliver');}}
function winServe(s){for(let i=0;i<3;i++){const t=s.story.event.tables[i];go(s,EVENT_SPOTS[`table${i}`]);action(s,'table',String(i));go(s,EVENT_SPOTS.pantry);action(s,'meal',RECIPES[t.recipe].id);go(s,EVENT_SPOTS[`table${i}`]);action(s,'table',String(i));assert.equal(storyEventAction(s,'table',String(i)).ok,false);tick(s,4.1);action(s,'table',String(i));}}
function winRace(s){for(let i=0;i<3;i++){go(s,EVENT_SPOTS[`checkpoint${i}`]);action(s,'parcel',String(i));}}
function winFight(s){let n=0;const e=s.story.event;while(e.status==='running'&&n++<1400){
 const t=e.elapsed,flight=storyDistance(e.actor,e.rivalActor)/9;e.aim={x:10+Math.sin((t+flight)*.65)*3,y:4+Math.sin((t+flight)*.4)*.8};
 if(e.throwCooldown===0)storyEventAction(s,'throw');if(e.warning&&e.warning.left<.2&&e.dodgeCooldown===0)storyEventAction(s,'dodge');storyTick(s,.05,{target:{x:t%6<3?6:14,y:9}});
 }assert.equal(e.status,'won',JSON.stringify(e.result));}
function win(s){({cook:winCook,serve:winServe,race:winRace,fight:winFight})[s.story.event.type](s);assert.equal(s.story.event.status,'won');assert.ok(validateSave(s));}
function business(s){const {story,revision,events,...rest}=s;return structuredClone(rest);}

test('Story ownership gates and declining leaves all ordinary progress untouched',()=>{const s=newGame(),before=structuredClone(s);assert.equal(startStory(s).ok,false);assert.deepEqual(s,before);s.basement.unlocked=true;s.basement.computer.owned=true;assert.equal(startStory(s).ok,false);s.basement.computer.email=true;const regular=business(s);assert.ok(startStory(s).ok);assert.deepEqual(business(s),regular);assert.deepEqual(s.story.emails,['intro']);startStory(s);assert.deepEqual(s.story.emails,['intro']);});
test('Version 10 and legacy saves gain an unstarted story without changing purchases or goods',()=>{const s=ready();s.money=543;s.player.bag=['controller'];s.pets.owned=['dog'];s.pets.equipped='dog';const old=structuredClone(s);old.version=10;delete old.story;const saved=JSON.stringify(old),decoded=decode(saved);assert.equal(decoded.version,11);assert.deepEqual(decoded.story,newStory());for(const k of ['player','money','pets','basement','floors','employees'])assert.deepEqual(decoded[k],s[k]);assert.equal(JSON.stringify(old),saved);});
test('Story freezes all businesses, employees, earnings, security and ordinary inventory',()=>{const s=ready();s.money=50000;command(s,{type:'hire',id:0});s.floors[0].cooking=true;s.floors[0].fry=10;s.player.bag=['controller','drink'];step(s,.1);startStory(s);leaveStoryComputer(s);const before=business(s);for(let i=0;i<300;i++){step(s,.1,{x:1,monitoring:true});storyTick(s,.1,{x:1});}assert.deepEqual(business(s),before);pauseStory(s);const t=s.time;step(s,.1);assert.ok(s.time>t);resumeStory(s);assert.deepEqual(s.player.bag,before.player.bag);});
test('Neighborhood paths reach every clue and entrance with character and pet clearance',()=>{for(const p of Object.values(STORY_PLACES)){assert.ok(storyWalkable('outside',p.x,p.y));assert.ok(storyPath('outside',STORY_PLACES.dfp,p).length);assert.ok(storyPath('outside',STORY_PLACES.dfp,p,.6).length);}for(const [type,ids] of [['cook',['batter','pixel','leaf','berry','prep','serve']],['serve',['pantry','table0','table1','table2']],['race',['checkpoint0','checkpoint1','checkpoint2']]])for(const id of ids)assert.ok(storyPath(type,{x:10,y:13.5},EVENT_SPOTS[id]).length);});
test('Challenge requires investigation and physical return to the computer; repeated sends do nothing',()=>{const s=ready();startStory(s);leaveStoryComputer(s);assert.equal(sendChallenge(s).ok,false);for(const id of ['crossing','rival']){go(s,STORY_PLACES[id]);assert.ok(storyVisit(s,id).ok);}assert.equal(sendChallenge(s).ok,false);go(s,STORY_PLACES.dfp);storyVisit(s,'dfp');assert.ok(sendChallenge(s).ok);assert.equal(sendChallenge(s).ok,false);assert.deepEqual(s.story.emails,['intro','challenge','reply']);assert.equal(storyObjective(s.story).id,'first-splat');});
test('Cooking enforces distance, recipe accuracy, actual preparation and receipt uniqueness',()=>{const s=ready();setObjective(s,'cook-off');startStoryEvent(s);assert.equal(storyEventAction(s,'ingredient','batter').ok,false);go(s,EVENT_SPOTS.prep);assert.equal(storyEventAction(s,'prepare','controller').ok,false);assert.equal(s.story.event.mistakes,1);action(s,'clear');for(const ingredient of RECIPES[0].ingredients){go(s,EVENT_SPOTS[ingredient]);action(s,'ingredient',ingredient);}go(s,EVENT_SPOTS.prep);action(s,'prepare','controller');action(s,'clear');assert.equal(s.story.event.cooking,null);winCook(s);assert.equal(s.story.event.score,30);assert.equal(storyEventAction(s,'deliver').ok,false);assert.equal(s.story.wins.filter(w=>w.id==='cook-off').length,1);});
test('Wrong orders and wrong addresses stay recoverable without a charge',()=>{const s=ready();setObjective(s,'lunch-rush');startStoryEvent(s);go(s,EVENT_SPOTS.table0);action(s,'table','0');go(s,EVENT_SPOTS.pantry);action(s,'meal','drink');go(s,EVENT_SPOTS.table0);assert.equal(storyEventAction(s,'table','0').ok,false);assert.equal(s.story.event.tables[0].state,'seated');assert.equal(s.story.event.dish,'drink');action(s,'clear');setObjective(s,'delivery-race');s.story.event=null;startStoryEvent(s);go(s,EVENT_SPOTS.checkpoint0);assert.equal(storyEventAction(s,'parcel','2').ok,false);assert.ok(s.story.event.penalty>=2);action(s,'parcel','0');assert.equal(s.story.event.checkpoint,1);assert.equal(s.money,120);});
test('All nine events are winnable at fixed basic speed without pet or permanent upgrades',()=>{for(const o of STORY_OBJECTIVES.filter(o=>o.kind==='event')){const s=ready();setObjective(s,o.id);assert.ok(startStoryEvent(s).ok);win(s);assert.equal(s.money,120);}});
test('Losses, ties and retries preserve earlier wins and cost nothing',()=>{for(const o of STORY_OBJECTIVES.filter(o=>o.kind==='event')){const s=ready();setObjective(s,o.id);startStoryEvent(s);const before=structuredClone(s.story.wins);tick(s,eventRules(o).limit+.1);assert.equal(s.story.event.status,'lost');assert.deepEqual(s.story.wins,before);assert.ok(startStoryEvent(s).ok);assert.deepEqual(s.story.wins,before);assert.equal(s.money,120);}
 const s=ready();setObjective(s,'delivery-race');startStoryEvent(s);const e=s.story.event;e.checkpoint=2;e.actor.x=15;e.actor.y=12;e.elapsed=eventRules(STORY_OBJECTIVES.find(o=>o.id===e.id)).rival;action(s,'parcel','2');assert.equal(e.status,'lost');});
test('Live pause retains event timers; serialization is pure; reloading offers a free restart',()=>{const s=ready();setObjective(s,'cook-off');startStoryEvent(s);tick(s,1);const event=structuredClone(s.story.event);pauseStory(s);tick(s,10);assert.deepEqual(s.story.event,event);resumeStory(s);tick(s,10,{paused:true});assert.deepEqual(s.story.event,event);const before=structuredClone(s);const raw=encode(s);assert.deepEqual(s,before);const restored=decode(raw);assert.equal(restored.story.event,null);assert.equal(restored.story.restart,'cook-off');assert.deepEqual(restored.story.wins,s.story.wins);assert.ok(startStoryEvent(restored).ok);assert.equal(restored.story.event.elapsed,0);});
test('Full campaign advances only after meaningful exploration and wins, then customers return',()=>{const s=ready();startStory(s);leaveStoryComputer(s);const before=business(s);while(!s.story.complete){const o=storyObjective(s.story);if(o.kind==='talk'){go(s,STORY_PLACES[o.place]);assert.ok(storyVisit(s,o.place).ok);}else if(o.kind==='mail'){go(s,STORY_PLACES.dfp);storyVisit(s,'dfp');assert.ok(sendChallenge(s).ok);leaveStoryComputer(s);}else{go(s,STORY_PLACES.arena);startStoryEvent(s);win(s);assert.ok(continueStory(s).ok);}}
 assert.equal(s.story.active,false);assert.equal(s.story.wins.length,9);assert.ok(s.story.emails.includes('victory'));assert.deepEqual(business(s),before);assert.ok(validateSave(s));const restored=decode(encode(s));assert.equal(restored.story.complete,true);step(restored,.1);assert.ok(restored.time>s.time);assert.equal(startStory(restored).ok,false);});
test('Story rejects malformed persistence and impossible skipped objectives',()=>{for(const mutate of [st=>st.index=8,st=>st.active=true,st=>st.emails=['fake'],st=>st.clock=NaN,st=>st.actor.x=-9,st=>st.restart='fake',st=>st.complete=true]){const st=newStory();mutate(st);assert.equal(validateStory(st),false);}const s=ready();setObjective(s,'first-splat');startStoryEvent(s);tick(s,3);assert.ok(validateSave(s));});

test('Every outfit uses outdoor collision bounds and seated guests face their story table',()=>{
 for(const outfit of OUTFITS)for(const reduced of [true,false]){
  const s=ready(),a={...s.story.actor,x:9.5,y:9.1,state:'dining',purpose:'story',table:0,needs:['controller'],delivered:[true]},m=character(outfit,0,'customer');s.settings.reducedMotion=reduced;
  const before=structuredClone(s),actorBefore=structuredClone(a),env={layout:[],walkable:(_,x,y)=>storyWalkable('serve',x,y),seat:()=>({x:9.5,y:9.1}),seatFacing:-Math.PI/2};
  for(let i=0;i<70;i++)animateStickman(m,a,a,s,.05,i*.05,()=>true,env);
  assert.ok(Math.abs(m.angle+Math.PI/2)<.02);assert.ok(m.sit>.9);m.root.traverse(o=>assert.ok([...o.position,...o.quaternion,...o.scale].every(Number.isFinite)));
  assert.deepEqual(a,actorBefore);assert.deepEqual(s,before);
 }
});
