import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync} from 'node:fs';
import {newGame,command,step} from '../src/simulation.js';
import {encode} from '../src/storage.js';

const url=process.env.DFP_TEST_URL||'http://127.0.0.1:4185',out=process.env.DFP_EVIDENCE_DIR||'artifacts/world-upgrade';mkdirSync(out,{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true}),checks=[],errors=[];let context,p;
async function launch(s,backup=false){if(context)await context.close();context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true});await context.addInitScript(({data,backup})=>{if(!sessionStorage.getItem('seed')){localStorage.setItem('dfp.save',backup?'corrupted':data);if(backup)localStorage.setItem('dfp.backup',data);sessionStorage.setItem('seed','1');}},{data:encode(s),backup});p=await context.newPage();p.on('pageerror',e=>errors.push(e.message));await p.clock.install();await p.goto(url);await p.locator('[data-station]').first().waitFor();await p.clock.runFor(100);}
const snapshot=()=>p.evaluate(()=>JSON.parse(JSON.parse(localStorage.getItem('dfp.save')).data));
const diagnostic=()=>p.locator('#game').evaluate(c=>c.dfpDiagnostics());
async function until(test,label,max=100){for(let i=0;i<max;i++){if(await test())return;await p.clock.runFor(50);}throw Error(label);}
function pass(name){checks.push(name);console.log('PASS',name);}
try{
 const fresh=newGame();fresh.money=600;await launch(fresh);await p.locator('#menu-button').tap();assert.equal(await p.locator('.unlock-progress').count(),2);await p.locator('[data-action="product"][data-id="controller"]').tap();await p.clock.runFor(100);await p.locator('[data-action="product"][data-id="drink"]').tap();await p.clock.runFor(100);await p.locator('[data-action="close"]').tap();await p.clock.runFor(150);
 const building=(await diagnostic()).stations.filter(s=>['prep','fry','pickup','drink'].includes(s.id));assert.ok(building.every(s=>s.building&&s.scale<1));await p.screenshot({path:`${out}/reveal.png`});await p.clock.runFor(900);assert.ok((await diagnostic()).stations.every(s=>!s.building&&s.scale===1&&s.y===0));assert.equal((await snapshot()).money,370);await p.reload();await p.clock.runFor(250);assert.ok((await diagnostic()).stations.every(s=>!s.building));assert.equal((await snapshot()).money,370);pass('Multiple unlocks reveal once, settle to fixed furniture, keep prices, and do not replay on reload');

 const payment=newGame();payment.money=1000;command(payment,{type:'product',id:'controller'});for(let i=0;i<380;i++)step(payment,.05,{pausedPlayer:true});payment.floors[0].customers=payment.floors[0].customers.slice(0,1);Object.assign(payment.floors[0].customers[0],{needs:['controller'],delivered:[true],state:'payment',x:5,y:10.5,path:[],pathKey:''});payment.floors[0].arrival=100;await launch(payment);assert.equal((await diagnostic()).stations.find(s=>s.id==='counter').pending,1);assert.equal((await diagnostic()).transfers,0);await p.locator('[data-station="counter"]').tap();await until(async()=>(await diagnostic()).transferKinds.includes('cash'),'Cash travels from collection point',180);const paid=await snapshot();assert.equal(paid.money,payment.money+5);assert.equal(await p.locator('#balance').textContent(),'$955');assert.equal(await p.locator('.money-feedback').textContent(),'+$5');await p.screenshot({path:`${out}/cash-collection.png`});
 const overlaps=await p.evaluate(()=>{const labels=[...document.querySelectorAll('.money-feedback')].filter(e=>!e.hidden),controls=[...document.querySelector('.play-area').querySelectorAll('button:not([hidden]),#joystick')].filter(e=>e.getClientRects().length);return labels.flatMap(e=>{const a=e.getBoundingClientRect();return controls.filter(el=>{const b=el.getBoundingClientRect();return a.left<b.right&&a.right>b.left&&a.top<b.bottom&&a.bottom>b.top;}).map(el=>el.id||el.dataset.station);});});assert.deepEqual(overlaps,[]);await p.reload();await p.clock.runFor(1500);assert.equal((await snapshot()).money,paid.money);assert.equal((await diagnostic()).transfers,0);pass('Green cash and +$5 label match one actual payout, avoid touch controls and cannot replay after reload');

 const drinks=newGame();drinks.money=1000;command(drinks,{type:'product',id:'controller'});command(drinks,{type:'product',id:'drink'});await launch(drinks);await p.locator('[data-station="drink"]').tap();await until(async()=>(await diagnostic()).stations.some(s=>s.id==='drink'&&s.pouring&&s.fill>.03),'Visible pour',180);await p.screenshot({path:`${out}/drink-pouring.png`});await until(async()=>(await snapshot()).player.bag.includes('drink'),'Drink transfer');await p.keyboard.press('Escape');await p.locator('[data-action="settings"]').tap();await p.locator('[data-action="motion"]').tap();await p.locator('[data-action="close"]').tap();await p.clock.runFor(250);assert.equal((await diagnostic()).transfers,0);assert.ok((await snapshot()).player.bag.includes('drink'));assert.equal(await p.locator('html').getAttribute('data-motion'),'reduced');pass('Drink visibly fills and transfers; reduced motion cancels decoration without losing goods');

 const cargo=newGame();cargo.player.bag=Array(8).fill('drink');cargo.floors[0].upgrades.capacity=5;cargo.money=4321;cargo.outfits.push('chef');cargo.outfit='chef';await launch(cargo,true);const d=await diagnostic(),a=d.positions.find(a=>a.key==='player');assert.equal(a.quantity,8);assert.equal(a.visibleGoods,4);assert.ok(a.carryHeight<.86);assert.equal(await p.locator('.quantity-badge').textContent(),'×8');assert.equal((await snapshot()).money,4321);assert.equal((await snapshot()).outfit,'chef');assert.deepEqual((await snapshot()).player.bag,cargo.player.bag);await p.screenshot({path:`${out}/bounded-carry.png`});await p.locator('[data-action="settings"]').tap();assert.match(await p.locator('#dialog-content').textContent(),/recovered from your backup/);pass('Eight-item carrying stays bounded and labeled; corrupt-primary recovery retains outfit, cash and goods');
 assert.deepEqual(errors,[]);writeFileSync(`${out}/world-browser.json`,JSON.stringify({checks,errors},null,2));
}finally{if(context)await context.close();await browser.close();}
