import * as T from 'three';
import {PETS,petById,petAbilities,equippedPet} from './pets.js';
import {petModel,animatePet} from './pet-models.js';
import {icon} from './icons.js';
import './pets.css';
const dollars=n=>`$${n.toLocaleString('en-US')}`;
export class PetShop{
 constructor(state,purchase){this.state=state;this.purchase=purchase;this.selected=state.pets.equipped??PETS[0].id;this.thumbs=new Map();this.last=0;this.angle=.3;}
 setup(){
  if(this.gl)return;this.canvas=document.createElement('canvas');this.canvas.setAttribute('aria-label','Animated 3D pet preview');this.canvas.setAttribute('role','img');
  this.gl=new T.WebGLRenderer({canvas:this.canvas,alpha:true,antialias:true,preserveDrawingBuffer:true});this.gl.setSize(320,270);this.gl.setPixelRatio(1);this.gl.outputColorSpace=T.SRGBColorSpace;this.gl.toneMapping=T.ACESFilmicToneMapping;this.gl.toneMappingExposure=1.2;
  this.scene=new T.Scene();this.scene.add(new T.HemisphereLight('#fff7dc','#c4b5df',2.7));const sun=new T.DirectionalLight('#fff3db',3);sun.position.set(-3,6,5);this.scene.add(sun);
  this.camera=new T.OrthographicCamera(-1.5,1.5,1.27,-1.27,.1,20);this.camera.position.set(2.1,1.9,4);this.camera.lookAt(0,.63,0);
  for(const p of PETS){const model=petModel(p);this.scene.add(model.root);animatePet(model,0,0,false,true);this.gl.render(this.scene,this.camera);this.thumbs.set(p.id,this.canvas.toDataURL('image/png'));this.scene.remove(model.root);}
  this.canvas.dfpDiagnostics=()=>({selected:this.selected,animatedModels:this.model?1:0,thumbnailCount:this.thumbs.size,calls:this.gl.info.render.calls,triangles:this.gl.info.render.triangles});
 }
 stateFor(p){const s=this.state,owned=s.pets.owned.includes(p.id),equipped=s.pets.equipped===p.id,reserve=!s.floors[0].products.controller?50:0,short=Math.max(0,p.price-s.money),held=!owned&&!short&&s.money-p.price<reserve;return {owned,equipped,blocked:!owned&&(short>0||held),label:equipped?'Equipped':owned?'Owned':short?'Locked':held?'Locked':'Buy',help:short?`Need ${dollars(short)} more`:held?'Keep $50 for your first food unlock':'',action:equipped?'pet-unequip':owned?'pet-equip':'pet-buy',button:equipped?'Unequip':owned?'Equip · Free':`Buy & equip · ${dollars(p.price)}`};}
 render(panel){
  this.setup();this.panel=panel;const scroll=panel.scrollTop,p=petById(this.selected),status=this.stateFor(p);
  panel.innerHTML=`<div class="panel-heading"><div><span class="eyebrow">A LITTLE COMPANY. A LITTLE EXTRA HELP.</span><h1>Your pixel pals.</h1><p>${PETS.length} companions. One by your side. Yours forever.</p></div></div><div class="pet-shop-layout"><aside class="pet-selected"><div class="pet-preview" style="--pet-color:${p.color}"></div><div class="pet-selected-body"><span class="pet-status" data-selected-status>${status.label}</span><h2>${p.name}</h2><strong class="pet-price">${dollars(p.price)}</strong><ul>${petAbilities(p).map(line=>`<li>${line}</li>`).join('')}</ul><p data-selected-help>${status.help}</p><button class="dark-button pet-purchase" data-pet-command="${status.action}" data-id="${p.id}" ${status.blocked?'disabled':''}>${status.button}</button><button class="outline-button pet-turn">Turn preview ${icon('arrow')}</button><p class="pet-wallet">Your money <b data-pet-balance>${dollars(this.state.money)}</b></p><p class="pet-rule">Helpers act only while you play upstairs. One task per cooldown, measured from you. Switching keeps cooldowns. No goods are created. Bonuses leave permanent upgrades unchanged.</p><p class="pet-active">Following you: <b>${equippedPet(this.state)?.name??'None'}</b></p><button class="outline-button pet-remove" ${this.state.pets.equipped?'':'hidden'}>Unequip current pet</button></div></aside><div class="pet-grid">${PETS.map(p=>{const st=this.stateFor(p);return `<article class="pet-card ${this.selected===p.id?'selected':''}" data-pet-card="${p.id}"><button class="pet-select" data-pet-select="${p.id}" aria-label="Preview ${p.name}" aria-pressed="${this.selected===p.id}" style="--pet-color:${p.color}"><img src="${this.thumbs.get(p.id)}" alt="${p.name}, ${p.id} companion" width="240" height="203"><span class="pet-status">${st.label}</span></button><div class="pet-card-body"><h2>${p.name}</h2><strong>${dollars(p.price)}</strong><ul>${petAbilities(p).map(line=>`<li>${line}</li>`).join('')}</ul><p class="pet-help">${st.help}</p><button class="outline-button" data-pet-command="${st.action}" data-id="${p.id}" ${st.blocked?'disabled':''}>${st.button}</button></div></article>`;}).join('')}</div></div>`;
  panel.querySelector('.pet-preview').append(this.canvas);this.canvas.setAttribute('aria-label',`Animated 3D preview of ${p.name}`);
  if(this.model?.definition.id!==p.id){if(this.model)this.scene.remove(this.model.root);this.model=petModel(p);this.model.reaction=1;this.scene.add(this.model.root);}
  panel.onclick=e=>{const select=e.target.closest('[data-pet-select]'),buy=e.target.closest('[data-pet-command]');if(select){this.selected=select.dataset.petSelect;this.render(panel);if(innerWidth<700)panel.scrollTop=0;return;}if(buy&&!buy.disabled){this.selected=buy.dataset.id;this.purchase({type:buy.dataset.petCommand,id:buy.dataset.id});this.model.reaction=1;return;}if(e.target.closest('.pet-turn'))this.angle+=Math.PI/2;if(e.target.closest('.pet-remove'))this.purchase({type:'pet-unequip'});};
  panel.scrollTop=scroll;this.key='';this.draw(0);
 }
 refresh(){
  if(!this.panel||this.panel.hidden||!this.panel.querySelector('.pet-shop-layout'))return;
  const s=this.state,key=`${s.money}/${s.pets.equipped}/${s.pets.owned.join()}/${s.floors[0].products.controller}`;if(this.key===key)return;this.key=key;
  for(const p of PETS){const st=this.stateFor(p),card=this.panel.querySelector(`[data-pet-card="${p.id}"]`);card.querySelector('.pet-status').textContent=st.label;card.querySelector('.pet-help').textContent=st.help;const b=card.querySelector('[data-pet-command]');b.disabled=st.blocked;b.dataset.petCommand=st.action;b.textContent=st.button;}
  const st=this.stateFor(petById(this.selected)),b=this.panel.querySelector('.pet-purchase');b.disabled=st.blocked;b.dataset.petCommand=st.action;b.textContent=st.button;this.panel.querySelector('[data-selected-status]').textContent=st.label;this.panel.querySelector('[data-selected-help]').textContent=st.help;this.panel.querySelector('[data-pet-balance]').textContent=dollars(s.money);this.panel.querySelector('.pet-active b').textContent=equippedPet(s)?.name??'None';this.panel.querySelector('.pet-remove').hidden=!s.pets.equipped;
 }
 draw(time){if(!this.model)return;const dt=this.last?Math.min(.1,(time-this.last)/1000):0;this.last=time;this.model.root.rotation.y=this.angle;animatePet(this.model,dt,time/1000,false,this.state.settings.reducedMotion);this.gl.render(this.scene,this.camera);}
}
